import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();
const sourcePath = path.join(repoRoot, "src/docs/catalog.json");
const generatedModulePath = path.join(repoRoot, "src/generated/docs-content.ts");
const generatedMarkdownPath = path.join(repoRoot, "public/generated/functionality-bdd.md");
const vedabaseMetadataPath = path.join(repoRoot, "data", "remote", "vedabase-dump", "metadata.json");
const youtubeMetadataPath = path.join(repoRoot, "data", "remote", "youtube-search", "metadata.json");
const syncReportPath = path.join(repoRoot, "data", "cache", "sync-report.json");

const rawSource = fs.readFileSync(sourcePath, "utf8");
const source = JSON.parse(rawSource);
const vedabaseMetadata = JSON.parse(fs.readFileSync(vedabaseMetadataPath, "utf8"));
const youtubeMetadata = JSON.parse(fs.readFileSync(youtubeMetadataPath, "utf8"));
const syncReport = JSON.parse(fs.readFileSync(syncReportPath, "utf8"));
const generatedAt = new Date().toISOString();

const payload = {
  generatedAt,
  product: source.product,
  datasourceStatus: {
    vedabase: vedabaseMetadata,
    youtube: youtubeMetadata,
    report: syncReport,
  },
  summary: {
    featureCount: source.features.length,
    scenarioCount: source.features.reduce(
      (count, feature) => count + feature.bddScenarios.length,
      0,
    ),
  },
  features: source.features,
};

const tsModule = `/* This file is auto-generated by scripts/generate-docs.mjs. Do not edit manually. */
export const documentationContent = ${JSON.stringify(payload, null, 2)} as const;
`;

const markdownSections = [
  "# Vedabase Functionality and BDD",
  "",
  `Generated at: ${generatedAt}`,
  "",
  `Documentation site path: ${source.product.sitePath}`,
  "",
  `Purpose: ${source.product.purpose}`,
  "",
  "## Datasource Status",
  "",
  `Vedabase dump: status=${vedabaseMetadata.status}, complete=${vedabaseMetadata.complete}, itemCount=${vedabaseMetadata.itemCount}, fetchedAt=${vedabaseMetadata.fetchedAt}`,
  `YouTube search cache: status=${youtubeMetadata.status}, complete=${youtubeMetadata.complete}, itemCount=${youtubeMetadata.itemCount}, fetchedAt=${youtubeMetadata.fetchedAt}`,
  "",
  `Feature count: ${payload.summary.featureCount}`,
  `BDD scenario count: ${payload.summary.scenarioCount}`,
  "",
  "## Phrase By Phrase",
  "",
  ...source.product.bilingualPhrases.map(
    (item) => `- ${item.emoji} ${item.en} ${item.ru}`,
  ),
  "",
  "## Programmatic Surface",
  "",
  "```text",
  ...source.product.programmaticSurface,
  "```",
  "",
  "## Global User Actions Diagram",
  "",
  "```mermaid",
  source.product.userActionDiagram.mermaid,
  "```",
  "",
  "## Pseudographic Screenshots",
  "",
];

for (const screenshot of source.product.screenshots) {
  markdownSections.push(`### ${screenshot.title}`);
  markdownSections.push("");
  markdownSections.push("```text");
  markdownSections.push(screenshot.art);
  markdownSections.push("```");
  markdownSections.push("");
}

for (const feature of source.features) {
  markdownSections.push(`## ${feature.title}`);
  markdownSections.push("");
  markdownSections.push(`Route: \`${feature.route}\``);
  markdownSections.push("");
  markdownSections.push(feature.summary);
  markdownSections.push("");
  markdownSections.push("### Capabilities");
  markdownSections.push("");
  markdownSections.push(...feature.capabilities.map((item) => `- ${item}`));
  markdownSections.push("");
  markdownSections.push("### User Actions");
  markdownSections.push("");
  markdownSections.push(...feature.userActions.map((item) => `- ${item}`));
  markdownSections.push("");
  markdownSections.push("### Acceptance Criteria");
  markdownSections.push("");
  markdownSections.push(...feature.acceptanceCriteria.map((item) => `- ${item}`));
  markdownSections.push("");
  markdownSections.push("### BDD Scenarios");
  markdownSections.push("");
  for (const scenario of feature.bddScenarios) {
    markdownSections.push(`#### ${scenario.title}`);
    markdownSections.push("");
    markdownSections.push(`- Given ${scenario.given}`);
    markdownSections.push(`- When ${scenario.when}`);
    markdownSections.push(`- Then ${scenario.then}`);
    markdownSections.push("");
  }
  markdownSections.push("### Mermaid Sequence");
  markdownSections.push("");
  markdownSections.push("```mermaid");
  markdownSections.push(feature.sequence.mermaid);
  markdownSections.push("```");
  markdownSections.push("");
}

fs.mkdirSync(path.dirname(generatedModulePath), { recursive: true });
fs.mkdirSync(path.dirname(generatedMarkdownPath), { recursive: true });
fs.writeFileSync(generatedModulePath, tsModule);
fs.writeFileSync(generatedMarkdownPath, `${markdownSections.join("\n").trim()}\n`);

console.log(`Generated docs module: ${path.relative(repoRoot, generatedModulePath)}`);
console.log(`Generated docs markdown: ${path.relative(repoRoot, generatedMarkdownPath)}`);
